
[methods.dbExecute]
description = """
Execute a database script directly on the specified live database.\n\nNote that this may not be
defined on all connectors.
"""
requestShape = "dbExecuteInput"
responseShape = "dbExecuteOutput"

[recordShapes.dbExecuteInput]
fields.datasourceType.shape = "dbExecuteDatasourceType"
fields.inputType.shape = "dbExecuteInputType"

[recordShapes.dbExecuteOutput]

[enumShapes.dbExecuteDatasourceType]
description = "The location of the live database to connect to in dbExecute."
variants.schema.description = "Path to the Prisma schema to take the datasource URL from."
variants.schema.shape = "string"
variants.url.description = "The URL of the database to run the command on."
variants.url.shape = "string"

[enumShapes.dbExecuteInputType]
description = "The input script for dbExecute."
variants.filePath = { shape = "string" }
variants.url = { shape = "string" }
