[methods.devDiagnostic]
description = """
The method called at the beginning of `migrate dev` to decide the course of
action based on the current state of the workspace.

It acts as a wrapper around diagnoseMigrationHistory. Its role is to interpret
the diagnostic output, and translate it to a concrete action to be performed by
the CLI.
"""
requestShape = "devDiagnosticInput"
responseShape = "devDiagnosticOutput"

[recordShapes.devActionReset.fields.reason]
shape = "string"

[recordShapes.devDiagnosticInput.fields.migrationsDirectoryPath]
shape = "string"

[recordShapes.devDiagnosticOutput.fields.action]
description = "The suggested course of action for the CLI."
shape = "devAction"

[enumShapes.devAction.variants.Reset]
shape = "devActionReset"

